---
title: "weekly checklist"
---

## Week 1

-   [x] weekly slides
-   [x] weekly reading
-   [x] weekly lab
-   [x] weekly lab solutions
-   [x] weekly lab repo
-   [x] weekly lab invite

## Week 2

-   [x] weekly slides
-   [x] weekly reading
    -   [x] links
    -   [x] readings
    -   [x] study guide
-   [x] weekly lab
-   [x] weekly lab solutions
-   [x] weekly lab repo
-   [x] weekly lab invite

## Week 3

-   [x] weekly slides
-   [x] weekly reading
    -   [x] links
    -   [x] readings
    -   [x] study guide
-   [x] weekly lab
-   [x] weekly lab solutions
-   [x] weekly lab repo
-   [x] weekly lab invite

## Week 4

-   [x] weekly slides
-   [x] weekly reading
    -   [x] links
    -   [x] readings
    -   [x] study guide
-   [x] weekly lab
-   [x] weekly lab solutions
-   [x] weekly lab repo
-   [x] weekly lab invite

## Week 5

-   [x] weekly slides
-   [x] weekly reading
    -   [x] links
    -   [x] readings
    -   [x] study guide
-   [x] weekly lab
-   [x] weekly lab solutions
-   [x] weekly lab repo
-   [x] weekly lab invite
-   [x] QUIZ #1

## Week 6

-   [x] weekly slides
-   [x] weekly reading
    -   [x] links
    -   [x] readings
    -   [x] study guide
-   [x] weekly lab
-   [x] weekly lab solutions
-   [x] weekly lab repo
-   [x] weekly lab invite

## Week 7

-   [x] weekly slides
-   [x] weekly reading
    -   [x] links
    -   [x] readings
    -   [x] study guide
-   [x] weekly lab
-   [x] weekly lab solutions
-   [x] weekly lab repo
-   [x] weekly lab invite

## Week 8

-   [x] weekly slides
-   [x] weekly reading
    -   [ ] links
    -   [x] readings
    -   [ ] study guide
-   [x] weekly lab
-   [x] weekly lab solutions
-   [ ] weekly lab repo
-   [ ] weekly lab invite
