---
title: "BSMM 8740 Syllabus"
---

[Click here](/documents/BSMM-8740-Fall%202025.pdf "PDF of syllabus") **to download a PDF copy of the syllabus.**

```{r}
#| echo: false
#| fig-align: "left"
require(magrittr, quietly = TRUE)
tbl_0 <- tibble::tribble(
~w,~x,
"Class section"	  ,"002", 
"Class meetings"	,"Wednesdays, 11:30 AM to 2:20 PM - Odette Building 507", 
"Instructor"	    ,"Dr. Lou Odette",
"Course Website"	,"https://brightspace.uwindsor.ca",
"Textbook"	      ,"The Elements of Statistical Learning - Data Mining, Inference, and Prediction. Second Edition by Hastie, Tibshirani, and Firedman.  \nAvailable for free at https://web.stanford.edu/~hastie/ElemStatLearn/" 
) %>% 
  gt::gt() %>% 
  gt::  tab_style(
    style = list(gt::cell_text(weight = "bold") )
    , locations = gt::cells_body( columns = c(w) )
  ) %>% 
   gt::cols_width(
    w ~ px(200),
    x ~ px(600),
  ) %>% 
  gt::tab_options(column_labels.hidden = TRUE, table.align = 'left') %>% 
  gtExtras::gt_theme_espn()

tbl_1 <- tibble::tribble(
~w,~x,~y,~z,
"Office hours"	                  ,"Thursday 2:00 PM" 	    ,"Office" ,"Zoom", 
"Telephone"	                    ," - " 	  ,"Email"	,"lodette@uwindsor.ca", 
"Academic Director"	            ,"Dr. Brent Furneaux"	,"Email"	,"brent.furneaux@uwindsor.ca:",
"Program Administrator"	        ,"TBD"	                ,"Email"	,"",
"Student Experience Coordinator"	,"Samantha DesRosiers" ,"Email"	,"Samantha.Desrosiers@uwindsor.ca",
"Career Advisor Coordinator"	    ,"Clementa Stan"	      ,"Email"	,"cstan@uwindsor.ca",
"Graduate Secretary"	            ,"Lisa Power"	        ,"Email"	,"lisa.power@uwindsor.ca"
) %>% 
  gt::gt() %>% 
  gt::  tab_style(
    style = list(gt::cell_text(weight = "bold") )
    , locations = gt::cells_body( columns = c(w,y) )
  ) %>% 
  gt::tab_options(column_labels.hidden = TRUE, table.align = 'left') %>% 
  gtExtras::gt_theme_espn()

gt::gt_group(tbl_0,tbl_1)
```

::: callout-note
***The University of Windsor sits on the traditional territory of the Three Fires Confederacy of First Nations, which includes the Ojibwa, the Odawa, and the Potawatomi. We respect the longstanding relationships with First Nations people in this place in the 100-mile Windsor-Essex peninsula and the straits – les détroits – of Detroit.***
:::

## Recording

Recording or reproduction of class sessions in whole or in part in any format including audio, video, or photographic format is not permitted without prior written permission from the course instructor or presenter. In addition, course materials cannot be shared, distributed, emailed, posted online, or otherwise disseminated or communicated in any form to any other person (including fellow classmates) unless written consent has first been obtained from the instructor or presenter. Course materials include but are not limited to slides, instructor notes, assignment instructions, audio and video recordings of course lectures, and audio and video recordings of software demonstrations.

## Calendar Description

This course is the exploration of an analytical framework for method selection and model building to help students develop professional capability in data-based techniques of data analytics. A focus will be placed on comparing and selecting appropriate methodology to conduct advanced statistical analysis and on building predictive modeling in order to create a competitive advantage in business operations with efficient analytical methods and data modeling.

## Learning Objectives & Expected Outcomes

The general objectives of this course are to:

-   Describe the concepts and issues associated with analytical framework for method selection and model building
-   Describe the assumptions, limitations, and advantages of various statistical techniques for building predictive models
-   Develop an understanding of various data analytics algorithms
-   Demonstrate a capacity for interpersonal interactions

## Master of Management Competencies

| **Program Competencies** | **Course Competencies** | Tested by |
|----------------------------|----------------------------|----------------|
| Apply an evidence-based decision model to evaluate and recommend the best available alternative to resolve an international business problem. | Apply an evidence-based decision model to evaluate and recommend the best available alternative to resolve an international business problem. | Lab Assessments |
| Analyze both qualitative and quantitative data and findings, distinguishing and evaluating their relevance to the resolution of international business issues. | Analyze both qualitative and quantitative data and findings, distinguishing and evaluating their relevance to the resolution of international business issues. | Quizzes, Midterm Examination, and Final Examination |

## Textbooks

While there is no official textbook for the course, the following textbooks are useful references for the class material, and additional suggested reading for each lecture can be found in the [**weekly materials**]{.underline}.

-   [The Elements of Statistical Learning Learning - Data Mining, Inference, and Prediction](https://web.stanford.edu/~hastie/ElemStatLearn) by Hastie, Tibshirani, and Firedman.

-   [r Data Science](https://r4ds.had.co.nz/) by Garret Grolemund and Hadley Wickham

-   [Introduction to Modern Statistics](https://openintro-ims.netlify.app/) by Mine Çetinkaya-Rundel and Johanna Hardin

-   [Tidy modeling with R](https://www.tmwr.org/) by Max Kuhn and Julia Silge

-   [Beyond Multiple Linear Regression](https://bookdown.org/roback/bookdown-BeyondMLR/) by Paul Roback and Julie Legler

## Course Content

| Date           | Topic                               |
|----------------|-------------------------------------|
| *Sep 10, 2025* | The Tidyverse, EDA & Git            |
| *Sep 17, 2025* | The Recipes Package                 |
| *Sep 24, 2025* | Regression Methods                  |
| *Oct 01, 2025* | The TidyModels Package              |
| *Oct 08, 2025* | Classification & Clustering Methods |
| *Oct 22, 2025* | Time Series Methods                 |
| *Oct 29, 2025* | Causality: DAGs                     |
| *Nov 05, 2025* | Causality: Methods                  |
| *Nov 12, 2025* | Monte Carlo Methods                 |
| *Nov 19, 2025* | Bayesian Methods                    |
| *Nov 26, 2025* | Advanced Topics                     |
| *Dec 03, 2025* | Final Exam                          |

## Key Dates For Exams/Assignments[^1]

[^1]: Lab assessments will be part of each class session.

| Date           | Exam/Assignment     |
|----------------|---------------------|
| *Oct 08, 2025* | Quiz1               |
| *Nov 05, 2025* | Midterm Examination |
| *Nov 19, 2025* | Quiz 2              |
| *Dec 03, 2025* | Final Examination   |

## Grading

|                         | \%  |
|-------------------------|-----|
| **Quizzes**             | 20  |
| **Lab Assessments**     | 30  |
| **Midterm Examination** | 25  |
| **Final Examination**   | 25  |
| **TOTAL**               | 100 |

## Grading Scale Policies

All course work is to be marked and final grades submitted using the 100% scale beginning September 1, 2013. In accordance with the Senate resolution, instructors are to submit whole numbers (e.g., 88, 76, etc.) as percentages. The following University-wide grade descriptors are in effect and will be printed on the back of transcripts:

| Letter Grade | Percentage Range |
|:------------:|------------------|
|      A+      | 90-100           |
|      A       | 85-89.9          |
|      A-      | 80-84.9          |
|      B+      | 77-79.9          |
|      B       | 73-76.9          |
|      B-      | 70-72.9          |
|      C+      | 67-69.9          |
|      C       | 63-66.9          |
|      C-      | 60-62.9          |
|      F       | 0-59.9           |

## Exam/Assignment Descriptions

The use of generative artificial intelligence (AI) tools is strictly prohibited in all course assessments unless explicitly indicated otherwise in guidelines provided by the instructor for an assessment. This includes the use of ChatGPT, Google Gemini, Claude, Jenni, Github Co-pilot, DaLL-E, Midjourney, and all other tools that provide artificial intelligence capabilities. When the use of generative AI is permitted this use must be acknowledged and cited following citation instructions given in the assessment guidelines. Use of generative AI outside of assessment guidelines or without required citation will constitute academic misconduct and may be subject to discipline under Bylaw 31: Academic Integrity. It is the student’s responsibility to be clear concerning constraints on the use of generative AI for each assessment and to comply with these constraints.

### **Quizzes**

The quizzes can consist of true/false, multiple choice, short answer, and essay questions from all material covered before the date of the quiz. When writing quizzes, you must abide by University of Windsor policies governing plagiarism and academic integrity. Quiz submissions may be subjected to review by automated tools to verify their originality.

### **Lab Assessments**

Lab assessments will require learners to demonstrate the ability to apply methods and techniques to machine learning problems using the R language and explain the steps they followed to solve a problem. Assessments should be started in person during lab sessions. Deadlines for each lab assessment will be posted.

### **Midterm Examination**

The midterm exam can consist of true/false, multiple choice, short answer, and essay questions from all material covered before the date of the mid-term exam. When writing this exam, you must abide by University of Windsor policies governing plagiarism and academic integrity. Exam submissions may be subjected to review by automated tools to verify their originality.

**Final Examination**

The final exam can consist of true/false, multiple choice, short answer, and essay questions covering all course material, including material discussed during lab sessions. When writing this exam, you must abide by University of Windsor policies governing plagiarism and academic integrity. Exam submissions may be subjected to review by automated tools to verify their originality.

## Odette School Of Business Course Policies

Please refer to the Odette School of Business Course Policies document for specific information on the following subjects. This Course Policies document is available electronically on each course website, on the Brightspace Master of Management Program page at <https://brightspace.uwindsor.ca/d2l/le/content/136263/viewContent/654482/View?ou=136263> and also in paper form outside each Area Secretary's office on the 4th floor of the Odette building. (Adopted Fall 2009).

## Master Of Management Program Etiquette

The Master of Management program is a culturally inclusive program where it is expected that students, faculty, and staff will recognize, appreciate, and benefit from diversity so as to enhance the learning experience. Promoting a culturally inclusive learning environment encourages individuals to collaborate and develop intercultural respect. The following outlines the protocol for Master of Management students while they are at the University of Windsor:

-   All students will communicate in English at all times. It is important for students to continually improve language skills and be inclusive of others from different backgrounds. 
-   Students will demonstrate respectful behavior toward their peers and professors, regardless of culture, language, values, beliefs, or ideas.

## Secondary Data Use, Evaluation, Focus Groups And Interviews

This course will be evaluated as part of internal or external quality assurance processes and reporting requirements to funding agencies and as research data for scholarly use. As a student in this course your online student data will be used for evaluating the course delivery and your engagement in the various aspects of the course. This will only occur after final grades have been submitted and approved so it will no effect on your grade. This course data provides information about your individual course usage and activity during the time that you are enrolled in the course. Your anonymized, aggregated data may also be used in the future in reports, articles or presentations.

During the final week of the course you may also be invited to participate in further research about the course. If you decide to participate you may be asked to fill out anonymous online questionnaires that solicit your impressions about the course design and student learning in the course.  The survey participation is voluntary and no questions of a personal nature will be asked. Your participation will have no effect on your grade and your instructor will not know who participated in the surveys.

Finally, at the end of the survey you may also be asked if you want to participate in a focus group or interviews after final grades have been assigned to gather yours and other student opinions about specific course delivery methods and technologies used.

## Commitment To Student Wellness:

**Feeling Overwhelmed?**

From time to time, students face obstacles that can affect academic performance. If you experience difficulties and need help, it is important to reach out to someone.

For help addressing mental or physical health concerns [on campus]{.underline}, contact (519) 253-3000: 

-   Student Health Services at ext. 7002 (<http://www.uwindsor.ca/studenthealthservices/>)

-   Student Counselling Centre at ext. 4616 (<http://www.uwindsor.ca/studentcounselling/>)

-   Peer Support Centre at ext. 4551

[**24 Hour Support is Available**]{.underline}

-   My Student Support Program (MySSP) is an immediate and fully confidential 24/7 mental health support that can be accessed for free through chat, online, and telephone. This service is available to all University of Windsor students and offered in over 30 languages. Call: 1-844-451-9700, visit <https://keepmesafe.myissp.com/>  or download the My SSP app: [Apple App Store](https://apps.apple.com/us/app/my-ssp/id1112006222 "https://apps.apple.com/us/app/my-ssp/id1112006222")/[Google Play](https://play.google.com/store/apps/details?id=com.onetapsolutions.morneau.myissp&hl=en).

A full list of on- and off-campus resources is available at  <http://www.uwindsor.ca/wellness>.

Should you need to request alternative accommodation contact your Instructor, Program Administrator, or Director.

## Lectures and labs

The goal of both the lectures and the labs is for them to be as interactive as possible. My role as instructor is to introduce you new tools and techniques, but it is up to you to take them and make use of them. A lot of what you do in this course will involve writing code, and coding is a skill that is best learned by doing. Therefore, as much as possible, you will be working on a variety of tasks and activities throughout each lecture and lab. You are expected to attend all lecture and lab sessions and meaningfully contribute to in-class exercises and discussion. Additionally, some lectures will feature \[application exercises\] that will be graded. In addition to application exercises will be periodic activities help build a learning community. These will be short, fun activities that will help everyone in the class connect throughout the semester.

You are expected to make use of the provided GitHub repository as your central code source platform. Commits to this repository will be used as a metric (one of several) of each team member's relative contribution for each project.

## Five tips for success

Your success on this course depends very much on you and the effort you put into it. The course has been organized so that the burden of learning is on you. Your TAs and I will help you be providing you with materials and answering questions and setting a pace, but for this to work you must do the following:

1.  Complete all the preparation work before class.
2.  Ask questions. As often as you can. In class, out of class. Ask me, ask the TAs, ask your friends, ask the person sitting next to you. This will help you more than anything else. If you get a question wrong on an assessment, ask us why. If you're not sure about the homework, ask. If you hear something on the news that sounds related to what we discussed, ask. If the reading is confusing, ask.
3.  Do the readings.
4.  Do the homework and lab.The earlier you start, the better. It's not enough to just mechanically plow through the exercises. You should ask yourself how these exercises relate to earlier material, and imagine how they might be changed (to make questions for an exam, for example.)
5.  Don't procrastinate. If something is confusing to you in Week 2, Week 3 will become more confusing, Week 4 even worse, and eventually you won't know where to begin asking questions. Don't let the week end with unanswered questions. But if you find yourself falling behind and not knowing where to begin asking, come to office hours, and let me help you identify a good (re)starting point.

### Policy on sharing and reusing code

I am well aware that a huge volume of code is available on the web to solve any number of problems. Unless I explicitly tell you not to use something, the course's policy is that you may make use of any online resources (e.g. RStudio Community, StackOverflow) but you must explicitly cite where you obtained any code you directly use (or use as inspiration). Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. On individual assignments you may not directly share code with another student in this class, and on team assignments you may not directly share code with another team in this class.

### Late work policy

The due dates for assignments are there to help you keep up with the course material and to ensure the teaching team can provide feedback within a timely manner. We understand that things come up periodically that could make it difficult to submit an assignment by the deadline. Note that the lowest homework and lab assignment will be dropped to accommodate such circumstances.

-   Homework and labs may be submitted up to 3 days late. There will be a 5% deduction for each 24-hour period the assignment is late.

-   There is no late work accepted for application exercises, since these are designed to help you prepare for labs and homework.

-   The late work policy for exams will be provided with the exam instructions.

-   The late work policy for the project will be provided with the project instructions.

### Waiver for extenuating circumstances

If there are circumstances that prevent you from completing a lab or homework assignment by the stated due date, you may email [Dr. Lou Odette](mailto:lodette@uwindsor.ca) **and** our head TA `TODO` before the deadline to waive the late penalty. In your email, you only need to request the waiver; you do not need to provide explanation. This waiver may only be used for once in the semester, so only use it for a truly extenuating circumstance.

### Attendance policy

Responsibility for class attendance rests with individual students. Since regular and punctual class attendance is expected, students must accept the consequences of failure to attend.

However, there may be many reasons why you cannot be in class on a given day, particularly with possible extra personal and academic stress and health concerns this semester. All course lectures will be recorded and available to enrolled students after class. If you miss a lecture, make sure to watch the recording and review the material before the next class session. Lab time is dedicated to working on your lab assignments and collaborating with your teammates on your project. If you miss a lab session, make sure to communicate with your team about how you can make up your contribution. Given the technologies we use in the course, this is straightforward to do asynchronously. If you know you're going to miss a lab session and you're feeling well enough to do so, notify your teammates ahead of time. Overall these policies are put in place to ensure communication between team members, respect for each others' time, and also to give you a safety net in the case of illness or other reasons that keep you away from attending class.

### Attendance policy related to COVID symptoms, exposure, or infection

Student health, safety, and well-being are the university's top priorities. To help ensure your well-being and the well-being of those around you, please do not come to class if you have symptoms related to COVID-19, have had a known exposure to COVID-19, or have tested positive for COVID-19. If any of these situations apply to you, you must follow university guidance related to the ongoing COVID-19 pandemic and current health and safety protocols. To keep the university community as safe and healthy as possible, you will be expected to follow these guidelines. Please reach out to me and your academic dean as soon as possible if you need to quarantine or isolate so that we can discuss arrangements for your continued participation in class.

### Inclement weather policy

In the event of inclement weather or other connectivity-related events that prohibit class attendance, I will notify you how we will make up missed course content and work. This might entail holding the class on Zoom synchronously or watching a recording of the class.

*Note:* If you've read this far in the syllabus, email me a picture of your pet if you have one or your favourite meme!

## Important Academic Dates

| FALL 2025                |                                      |
|--------------------------|--------------------------------------|
| September 2              | Labour Day (University closed)       |
| September 5              | all 2025 classes begin               |
| September 18             | Add/Drop Date                        |
| October 3                | Financial Drop Date                  |
| October 14               | Thanksgiving Day (University closed) |
| October 12 - 20          | Reading Week (no classes)            |
| November 13              | Voluntary Withdrawal Date            |
| December 4               | Classes end                          |
| December 7               | Final Exams Begin                    |
| December 18              | Final Exams End                      |
| December 19              | Alternate Final Exam Day             |
| December 23 -- January 1 | University closed -- Winter holiday  |

## 
