---
title: "FAQ"
---

## Can I use generative AI for class assignments?

Generative Artificial Intelligence (AI) models, such as ChatGPT, Google Gemini, Claude, Jenni, Github Co-pilot, DaLL- E, and Midjourney, may be used for any lab assignment in this course with appropriate acknowledgement and citation. Examples of citing AI language models are available [here](http://libguides.umn.edu/chatgpt). You are responsible for fact-checking statements and code composed by AI language models. Failure to acknowledge or cite GAI use will constitute academic misconduct and may be subject to discipline under Bylaw 31: Academic Integrity.

Use of Generative Artificial Intelligence (AI) models will not be permitted for quizzes, or exams.

## Can I use a local install of R and RStudio instead of using the Lab?

The short answer is, I'd rather you didn't, to save yourself some headache. But, the long answer is, sure! But you will need to install a specific versions of R and RStudio for everything to work as expected. You will also need to install the R packages we're using as well as have Git installed on your computer. These are not extremely challenging things to get right, but they are not trivial either, particularly on certain operating systems. Myself and the TA are always happy to provide help with any computational questions when you're working in the lab. If you're working on your local setup, we can't guarantee being able to resolve your issues, though we're happy to try.

If you want to take this path, here is what you need to do:

-   Download and install R 4.5: <https://cran.r-project.org/>
-   Download and install a daily build of RStudio: <https://dailies.rstudio.com/>
-   Install Git: <https://happygitwithr.com/install-git.html>
-   Install any necessary packages with `install.packages("___")`

And I'd like to reiterate again that successful installation of these software is **not** a learning goal of this course.

## Can I use a local install of R and RStudio for exams and quizzes?

The short answer is [**no**]{.underline}, to save both of us a headache. The machines in the Lab have the vast majority of the packages required, and given the time pressures of lab assessments, neither of us has the time to debug problems on your machine.
